name: config
spec:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 127.0.0.1, port_value: 9000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: "tcp_proxy"
                cluster: cluster_0
  clusters:
    - name: cluster_0
      connect_timeout: 2s
      load_assignment:
        cluster_name: cluster_0
      lb_policy: MAGLEV
      common_lb_config:
        healthy_panic_threshold: 0
      health_checks:
        - timeout: 1s
          interval: 10s
          unhealthy_threshold: 2
          healthy_threshold: 2
          http_health_check:
            path: /health
      maglev_lb_config:
        table_size: 86243